
import java.text.MessageFormat;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Logger;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER E5-471
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        SetTanggal();
    }

    /**
   
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        makan = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jmlmakan = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb1data = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        th = new javax.swing.JButton();
        total = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        tgl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setText("WAROENG GENDOET");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("The Real Jawa Food");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(315, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(255, 255, 255))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(323, 323, 323))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 10, 880, 70);

        jLabel3.setFont(new java.awt.Font("Square721 Cn BT", 0, 18)); // NOI18N
        jLabel3.setText("Pesan Menu");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 90, 170, 22);
        getContentPane().add(makan);
        makan.setBounds(220, 130, 140, 40);

        jButton1.setFont(new java.awt.Font("SketchFlow Print", 0, 18)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(450, 330, 80, 40);

        jButton5.setFont(new java.awt.Font("SketchFlow Print", 0, 13)); // NOI18N
        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(560, 330, 80, 40);

        jButton3.setFont(new java.awt.Font("SketchFlow Print", 0, 13)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(670, 330, 80, 40);

        jButton6.setFont(new java.awt.Font("SketchFlow Print", 0, 13)); // NOI18N
        jButton6.setText("Print");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(770, 330, 80, 40);

        jLabel9.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 16)); // NOI18N
        jLabel9.setText("Makanan + Minuman");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 130, 170, 30);

        jLabel10.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 16)); // NOI18N
        jLabel10.setText("Jumlah Item");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 190, 110, 30);
        getContentPane().add(jmlmakan);
        jmlmakan.setBounds(220, 180, 140, 40);

        tb1data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Item", "Jml Item", "Harga", "Total Harga"
            }
        ));
        jScrollPane3.setViewportView(tb1data);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(380, 120, 500, 180);

        jLabel4.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 16)); // NOI18N
        jLabel4.setText("Total Harga");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 300, 120, 30);

        th.setText("Total Harga");
        th.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thActionPerformed(evt);
            }
        });
        getContentPane().add(th);
        th.setBounds(110, 390, 116, 44);
        getContentPane().add(total);
        total.setBounds(220, 300, 140, 40);

        jLabel11.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 16)); // NOI18N
        jLabel11.setText("Harga");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 240, 120, 30);
        getContentPane().add(harga);
        harga.setBounds(220, 240, 140, 40);

        tgl.setText("Tanggal");
        getContentPane().add(tgl);
        tgl.setBounds(690, 90, 110, 20);

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(20, 90, 890, 390);

        setSize(new java.awt.Dimension(936, 541));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        makan.setText("");
        jmlmakan.setText("");
        harga.setText("");
        total.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    
    private void selectdata(){
    String kolom[]={"makan", "jmlmakan","harga","total"};
    DefaultTableModel dtm = new DefaultTableModel (null,kolom);
    String SQL = "SELECT * FROM menu";
    ResultSet rs = KoneksiDB.executeQuery(SQL);
    try{
    while(rs.next()){
        String item = rs.getString(1);
        String jml_item = rs.getString(2);
        String harga = rs.getString(3);
        String total_harga = rs.getString(4);
            String data[] = {item , jml_item , harga , total_harga};
            dtm.addRow(data);
    }
    } catch(SQLException ex){
        
    Logger.getLogger(menu.class.getName()).log(Level.SEVERE,null, ex);
    
    } tb1data.setModel(dtm);
    
    }
    
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int baris = tb1data.getSelectedRow();
        if (baris != -1){
            String Makanan = tb1data.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM login WHERE Makanan='"+Makanan+"'";
            int status = KoneksiDB.execute(SQL);
            if(status==1){
                JOptionPane.showMessageDialog(this,"Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Waroeng Gendoet");
        MessageFormat footer = new MessageFormat ("Page (0,number, Integer)");
        try{
            tb1data.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true,null);
        }catch (java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%s", e.getMessage());
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          if ("".equals(makan.getText()) || "".equals(jmlmakan.getText()) || harga.getText().equals("") ) 
        {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
              int harga = Integer.parseInt(String.valueOf(jmlmakan.getText()));
              int jml = Integer.parseInt(String.valueOf(harga));
          }
            String SQL = "INSERT INTO menu(item, jml_item, harga, total_harga) VALUES ('"+makan.getText()+"','"+jmlmakan.getText()+"','"+harga.getText()+"','"+total.getText()+"')";
            int status = KoneksiDB.execute(SQL);
            if(status == 1){
                JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectdata();
            } else {
                JOptionPane.showMessageDialog(this, "Data Gagal Ditambahkan", "Gagal", JOptionPane.INFORMATION_MESSAGE);
            }
        
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SetTanggal(){
    java.util.Date now = new java.util.Date();
    java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("yyy/MM/dd");
    tgl.setText(kal.format(now));
    
    }
    
    private void thActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thActionPerformed
        // TODO add your handling code here:
            int jmlBarang = Integer.parseInt(jmlmakan.getText());
            int hargaBarang = Integer.parseInt(harga.getText());
            int totalBiaya = jmlBarang*hargaBarang;
        if (totalBiaya > 200000){
            int diskon = totalBiaya*10/100;
            total.setText(String.valueOf(totalBiaya-diskon));
        }else
        total.setText(String.valueOf(totalBiaya));
    }//GEN-LAST:event_thActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField harga;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jmlmakan;
    private javax.swing.JTextField makan;
    private javax.swing.JTable tb1data;
    private javax.swing.JLabel tgl;
    private javax.swing.JButton th;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables

}
